# Generated by Django 3.0.5 on 2020-04-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('jp', models.CharField(max_length=100)),
                ('kana', models.CharField(max_length=100)),
                ('romam', models.CharField(max_length=100)),
                ('disp', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
