# Generated by Django 3.0.5 on 2020-04-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JapanInfectedNumber',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
            ],
        ),
    ]
