# Generated by Django 3.0.5 on 2020-04-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddb', '0002_japaninfectednumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='japaninfectednumber',
            name='num',
        ),
        migrations.AddField(
            model_name='japaninfectednumber',
            name='death',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='japaninfectednumber',
            name='discharge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='japaninfectednumber',
            name='hospitalization',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='japaninfectednumber',
            name='positive',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='japaninfectednumber',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='japaninfectednumber',
            name='state',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
