# Generated by Django 3.0.5 on 2020-04-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddb', '0003_auto_20200408_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japaninfectednumber',
            name='state',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
