# Generated by Django 3.0.5 on 2020-04-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddb', '0006_auto_20200408_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japaninfectednumber',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
