# Generated by Django 3.0.5 on 2020-04-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddb', '0007_auto_20200408_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
