# Generated by Django 3.0.5 on 2020-04-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddb', '0008_auto_20200408_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='japaninfectednumber',
            name='date',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
