# Generated by Django 3.0.5 on 2020-04-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japaninfectednumber',
            name='date',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
