# Generated by Django 3.0.5 on 2020-04-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddb', '0003_auto_20200408_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='japaninfectednumber',
            name='state_id',
            field=models.IntegerField(null=True),
        ),
    ]
