# Generated by Django 3.0.5 on 2020-04-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddb', '0004_japaninfectednumber_state_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfectedPerson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(default='', max_length=16)),
                ('pat_id', models.IntegerField()),
                ('city_no', models.CharField(default='', max_length=16)),
                ('announce_date', models.CharField(default='', max_length=10)),
                ('infected_date', models.CharField(default='', max_length=10)),
                ('living_state', models.CharField(default='', max_length=24)),
                ('living_city', models.CharField(default='', max_length=24)),
                ('age', models.IntegerField(default=999)),
                ('sex', models.IntegerField(default=2)),
                ('status', models.CharField(default='', max_length=24)),
                ('symptoms', models.CharField(default='', max_length=128)),
                ('occupation', models.CharField(default='', max_length=24)),
                ('close_contact', models.CharField(default='', max_length=64)),
                ('rel_close_contact', models.CharField(default='', max_length=256)),
                ('travel_history', models.IntegerField()),
                ('travel_destination', models.CharField(default='', max_length=128)),
                ('remarks', models.CharField(default='', max_length=2048)),
                ('cluster_location', models.CharField(default='', max_length=128)),
                ('cluster_name', models.CharField(default='', max_length=256)),
                ('discharge', models.IntegerField()),
                ('death', models.IntegerField()),
                ('death_date', models.CharField(default='', max_length=10)),
                ('full_presentation', models.CharField(default='', max_length=8096)),
            ],
        ),
    ]
