# Generated by Django 3.0.5 on 2020-04-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddb', '0007_auto_20200410_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectedperson',
            name='age',
            field=models.IntegerField(default=999, null=True),
        ),
        migrations.AlterField(
            model_name='infectedperson',
            name='sex',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
