# Generated by Django 3.0.5 on 2020-04-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddb', '0009_auto_20200411_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectedperson',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
