# Generated by Django 3.0.5 on 2020-04-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddb', '0010_auto_20200411_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='japaninfectednumber',
            name='discharge_per',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='japaninfectednumber',
            name='plus',
            field=models.IntegerField(null=True),
        ),
    ]
