# Generated by Django 3.0.5 on 2020-04-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddb', '0011_auto_20200411_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='japaninfectednumber',
            old_name='plus',
            new_name='positive_plus',
        ),
        migrations.AddField(
            model_name='japaninfectednumber',
            name='death_per',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='japaninfectednumber',
            name='hospitalization_per',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='japaninfectednumber',
            name='positive_per',
            field=models.FloatField(null=True),
        ),
    ]
